import './globals.css'
import { Inter } from 'next/font/google'
import Menu from './components/Menu'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className + " bg-white flex"}>
        <Menu />
        <main className="flex-1">{children}</main>
        </body>
    </html>
  )
}
